// Runtime configuration values populated from AMReX ParmParse.
struct RunConfig {
  int max_step = 8;
  int max_grid_size = 32;
  int plot_int = 8;
  int toro_test = 1;
  int spatial_order = 1;
  amrex::Real stop_time = 0.05;
  amrex::Real gamma = 1.4;
  amrex::Real cfl = 0.4;
  amrex::Real imex_cfl = 0.8;
  amrex::Real imex_acoustic_cfl_cap = 0.0;
  amrex::Real imex_solver_tol = 1.0e-10;
  amrex::Real velocity_x = 1.0;
  amrex::Real velocity_y = 0.5;
  amrex::Real density_inner = 2.0;
  amrex::Real density_outer = 1.0;
  amrex::Real pressure = 1.0;
  amrex::Real mach = 0.1;
  amrex::Real blob_cx = 0.35;
  amrex::Real blob_cy = 0.35;
  amrex::Real blob_radius = 0.15;
  amrex::Real vortex_cx = 0.0;
  amrex::Real vortex_cy = 0.0;
  amrex::Real isentropic_vortex_strength = 5.0;
  amrex::Real riemann_interface_x = 0.5;
  amrex::Real riemann_interface_y = 0.5;
  int imex_solver_max_iter = 100;
  int imex_solver_verbose = 0;
  int imex_acoustic_startup = 1;
  int imex_picard_extra_iterations = 1;
  int imex_picard_iterations = 2;
  amrex::Real bdltv20_paper_t1_s2_dt = -1.0;
  amrex::Real bdltv20_paper_epsilon = 1.0;
  int bdltv20_paper_t1_s2_max_steps = 4096;
  ProblemKind problem = ProblemKind::AdvectionBlob;
  RiemannKind riemann = RiemannKind::Hllc;
  MethodKind method = MethodKind::Explicit;
  ImexFormKind imex_form = ImexFormKind::Bdltv20T1S2SourceMapPicard;
  SlopeLimiterKind slope_limiter = SlopeLimiterKind::Minmod;
  ImexPredictorDissipationKind imex_predictor_dissipation = ImexPredictorDissipationKind::Material;
  std::array<int, AMREX_SPACEDIM> n_cell{{64, 64}};
  std::array<int, AMREX_SPACEDIM> is_periodic{{1, 1}};
  std::array<amrex::Real, AMREX_SPACEDIM> prob_lo{{0.0, 0.0}};
  std::array<amrex::Real, AMREX_SPACEDIM> prob_hi{{1.0, 1.0}};
  std::string plot_file = "plt";
  std::string final_csv;
  std::string field_boundary = "outflow";
  std::string imex_pressure_solver_path = "host_single_level_gmres";
  std::string imex_pressure_stabilization = "off";
  std::string bdltv20_paper_t1_s2 = "off";
  std::string bdltv20_paper_pressure_solver = "gmres";
  std::string shock_density_bubble_snapshot_dir;
  std::string shock_density_bubble_snapshot_times = "0,0.06,0.12,0.18,0.24,0.30";
};
